// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bucket as shown in the bucket list.
 */
export type BucketSummaryDto = { 
/**
 * Bucket name.
 */
name: string, 
/**
 * Creation time as RFC 3339, when the backend reports one.
 */
createdAt?: string, };

/**
 * Result of a whole-bucket usage scan.
 */
export type BucketUsageDto = { 
/**
 * The measured bucket.
 */
scope: UsageScopeDto, 
/**
 * When the scan finished, as RFC 3339.
 */
scannedAt?: string, };

/**
 * Per-bucket outcome of a cleanup deletion.
 */
export type CleanupBucketDeleteResultDto = { 
/**
 * Bucket the keys belonged to.
 */
bucket: string, 
/**
 * Keys removed.
 */
deleted: Array<string>, 
/**
 * Keys that survived.
 */
failed: Array<KeyFailureDto>, };

/**
 * A single object proposed for cleanup.
 */
export type CleanupCandidateDto = { 
/**
 * Bucket holding the object.
 */
bucket: string, 
/**
 * Full object key.
 */
key: string, 
/**
 * Size in bytes.
 */
sizeBytes: number, 
/**
 * Last modification time as RFC 3339.
 */
lastModified?: string, 
/**
 * Storage class, when reported.
 */
storageClass?: string, 
/**
 * Why this object was ranked as a candidate.
 */
reasons: Array<string>, };

/**
 * One object a cleanup deletion should remove.
 */
export type CleanupDeleteTargetDto = { 
/**
 * Bucket holding the object.
 */
bucket: string, 
/**
 * Full object key.
 */
key: string, };

/**
 * A completed cleanup plan.
 */
export type CleanupPlanDto = { 
/**
 * Ranked candidates, best first.
 */
candidates: Array<CleanupCandidateDto>, 
/**
 * Aggregate counts.
 */
summary: CleanupPlanSummaryDto, 
/**
 * Buckets that could not be scanned.
 */
warnings: Array<CleanupWarningDto>, 
/**
 * When the scan finished, as RFC 3339.
 */
scannedAt?: string, };

/**
 * Aggregate counts for a completed scan.
 */
export type CleanupPlanSummaryDto = { 
/**
 * Buckets successfully walked.
 */
scannedBuckets: number, 
/**
 * Objects inspected.
 */
scannedObjects: number, 
/**
 * Candidates returned.
 */
candidateCount: number, 
/**
 * Combined size of the returned candidates.
 */
candidateTotalSize: number, };

/**
 * Filters submitted with a cleanup scan.
 */
export type CleanupScanRequest = { 
/**
 * Restrict to one bucket; omit to scan every accessible bucket.
 */
bucket?: string, 
/**
 * Restrict to a key prefix.
 */
prefix?: string, 
/**
 * Keep objects at least this large.
 */
minSizeBytes?: number, 
/**
 * Keep objects last modified strictly before this RFC 3339 instant.
 */
olderThanIso?: string, 
/**
 * Cap on returned candidates.
 */
maxResults: number, };

/**
 * A bucket that could not be scanned.
 */
export type CleanupWarningDto = { 
/**
 * Bucket that failed.
 */
bucket: string, 
/**
 * Why it failed.
 */
message: string, };

/**
 * A folder row produced by the listing delimiter.
 */
export type CommonPrefixDto = { 
/**
 * Full prefix, including its trailing delimiter.
 */
prefix: string, 
/**
 * Basename relative to the listed prefix.
 */
name: string, };

/**
 * A candidate connection submitted by the connection form.
 */
export type ConnectionRequest = { 
/**
 * Base URL of the endpoint.
 */
endpoint: string, 
/**
 * Access key identifier.
 */
accessKeyId: string, 
/**
 * Secret access key.
 */
secretAccessKey: string, 
/**
 * Signing region; defaults to `us-east-1` when omitted.
 */
region?: string, 
/**
 * Path-style addressing; defaults to enabled.
 */
forcePathStyle?: boolean, 
/**
 * Skip TLS verification; defaults to disabled.
 */
skipTlsVerification?: boolean, };

/**
 * Keys a delete request should remove.
 */
export type DeleteObjectsRequest = { 
/**
 * Full object keys.
 */
keys: Array<string>, };

/**
 * Outcome of a batch delete.
 */
export type DeleteResultDto = { 
/**
 * Keys the backend confirmed as removed.
 */
deleted: Array<string>, 
/**
 * Keys that survived.
 */
failed: Array<KeyFailureDto>, };

/**
 * A key that could not be acted on.
 */
export type KeyFailureDto = { 
/**
 * The key that failed.
 */
key: string, 
/**
 * Why it failed.
 */
message: string, };

/**
 * One object to relocate.
 */
export type MoveEntryDto = { 
/**
 * Current key.
 */
key: string, 
/**
 * Key the object should end up at.
 */
destinationKey: string, };

/**
 * A batch move request.
 */
export type MoveObjectsRequest = { 
/**
 * Bucket the objects are read from.
 */
sourceBucket: string, 
/**
 * Bucket the objects are written to.
 */
destinationBucket: string, 
/**
 * The objects to relocate.
 */
entries: Array<MoveEntryDto>, };

/**
 * Outcome of a batch move.
 */
export type MoveResultDto = { 
/**
 * Objects that were relocated.
 */
moved: Array<MovedObjectDto>, 
/**
 * Objects that stayed put.
 */
failed: Array<KeyFailureDto>, };

/**
 * An object that reached its destination.
 */
export type MovedObjectDto = { 
/**
 * Original key.
 */
key: string, 
/**
 * Key it now lives at.
 */
destinationKey: string, };

/**
 * One page of a listing.
 */
export type ObjectListPageDto = { 
/**
 * Bucket that was listed.
 */
bucket: string, 
/**
 * Prefix that was listed.
 */
prefix: string, 
/**
 * Delimiter used.
 */
delimiter: string, 
/**
 * Folder rows.
 */
prefixes: Array<CommonPrefixDto>, 
/**
 * Object rows.
 */
objects: Array<ObjectSummaryDto>, 
/**
 * Whether the backend has more to give.
 */
isTruncated: boolean, 
/**
 * Token for the next page.
 */
continuationToken?: string, 
/**
 * Keys the backend reported for this page.
 */
keyCount: number, };

/**
 * A single object row.
 */
export type ObjectSummaryDto = { 
/**
 * Full object key.
 */
key: string, 
/**
 * Basename relative to the listed prefix.
 */
name: string, 
/**
 * Size in bytes.
 *
 * Declared as a TypeScript `number` rather than the `bigint` ts-rs would
 * infer: serde writes a plain JSON number, and the existing components do
 * arithmetic on it. Exactness holds to 2^53 bytes, far beyond any object a
 * backend can store.
 */
size: number, 
/**
 * Last modification time as RFC 3339.
 */
lastModified?: string, 
/**
 * Storage class, when reported.
 */
storageClass?: string, 
/**
 * Entity tag, when reported.
 */
etag?: string, };

/**
 * Breakdown of a location by what it directly contains.
 */
export type PrefixUsageDto = { 
/**
 * Human label for the location.
 */
scope: string, 
/**
 * Direct children, largest first.
 */
entries: Array<PrefixUsageEntryDto>, 
/**
 * Combined size beneath the location.
 */
totalSize: number, 
/**
 * Objects beneath the location.
 */
objectCount: number, 
/**
 * Whether the breakdown stopped recording new children.
 */
truncated: boolean, };

/**
 * Usage of one immediate child of a scanned location.
 */
export type PrefixUsageEntryDto = { 
/**
 * Name relative to the scanned prefix.
 */
name: string, 
/**
 * Whether this aggregates a sub-tree.
 */
isPrefix: boolean, 
/**
 * Combined size in bytes.
 */
totalSize: number, 
/**
 * Objects counted.
 */
objectCount: number, };

/**
 * An object to sign a download URL for.
 */
export type PresignRequest = { 
/**
 * Full object key.
 */
key: string, 
/**
 * Lifetime in seconds; the server clamps it.
 */
expiresIn?: number, };

/**
 * A signed download URL.
 */
export type PresignedUrlDto = { 
/**
 * The signed URL.
 */
url: string, };

/**
 * The non-secret half of a session, safe to hand the browser.
 *
 * The endpoint and addressing style are included because the client builds
 * direct download URLs from them, exactly as the Next.js page did. Neither key
 * is ever part of this shape.
 */
export type SessionDto = { 
/**
 * Whether a usable connection is stored.
 */
connected: boolean, 
/**
 * Endpoint of the active connection.
 */
endpoint?: string, 
/**
 * Region of the active connection.
 */
region?: string, 
/**
 * Whether the active connection uses path-style addressing.
 */
forcePathStyle?: boolean, 
/**
 * Whether the active connection skips TLS verification.
 */
skipTlsVerification?: boolean, 
/**
 * Access key identifier with all but its leading characters masked.
 *
 * Masked here rather than in the browser so the full identifier never
 * leaves the server, even though it is the less sensitive half of the pair.
 */
accessKeyIdMasked?: string, 
/**
 * When the session was established, as RFC 3339.
 */
createdAt?: string, 
/**
 * When the session was last used, as RFC 3339.
 */
lastUsedAt?: string, 
/**
 * Endpoint the connection form prefills.
 */
defaultEndpoint: string, };

/**
 * Measured usage for one scope.
 */
export type UsageScopeDto = { 
/**
 * What was measured.
 */
scope: string, 
/**
 * Total size in bytes.
 */
totalSize: number, 
/**
 * Objects counted.
 */
objectCount: number, };
