apiVersion: v1
kind: Service
metadata:
  name: inari
  namespace: inari
  labels:
    app.kubernetes.io/name: inari
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: inari
  ports:
    - name: http
      port: 80
      targetPort: http
